server:
  port: 8080

spring:
  application:
    name: testLatticeApp
  datasource:
    url: jdbc:mariadb://localhost:3306/hunter_2020
    username: mybb
    password: changeme
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    prefix=classpath:/templates/

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true